%%%                                                         AMBIENTE DE TESTES
%%% 
%%% UTILIZA ESSE SCRIPT PARA TESTES, NÃO CRIE OUTROS
%%% PARA MELHOR FLEXBILIDADE CRIEI OS SCRIPTS Tests PARA FACILITAR
%%%
%%% FAVOR APAGAR O CODIGO APOS UTILIZAR O SCRIPT